### ISSUE TITLE
Log file should not hard code /data to write error logs

### ISSUE THREAD

**Issue by jbutcher21** [senzing-garage/file-loader#105]
It throws an error if you try to use file-loader in another container that should write the logs elsewhere.

**Comment by antaenc** [comment]
This is from the prior version of file_loader where /data is used as a volume mount for input files and/or output files. I've added a small check to V4 sz_file_loader that if it is running in Docker and /data exists (.e.g., a volume mount is used on the docker run command to /data) it will be used otherwise the files are written to CWD.
